# Datenbank-Einstellungen
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/nethera
quarkus.datasource.username=nethera
quarkus.datasource.password=nethera

# ORM / Schema-Generierung (dev-friendly)
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

nethera.router.ip=192.168.1.1
nethera.router.ssh-key-path=/Users/tobi/.ssh/id_ed25519_router